import os

from dotenv import load_dotenv
from openai import OpenAI


load_dotenv()


def create_client():
    """
    Create an OpenAI client using the API key from environment variables.

    Returns:
        An initialized OpenAI client.

    Raises:
        ValueError: If the OpenAI API key is not configured.
    """
    api_key = os.getenv("OPENAI_API_KEY")

    if not api_key:
        raise ValueError(
            "OPENAI_API_KEY is not configured. "
            "Add it to the .env file."
        )

    return OpenAI(api_key=api_key)


client = create_client()


def generate_answer(prompt, model="gpt-5.6-luna"):
    """
    Generate an answer using an OpenAI language model.

    Args:
        prompt: The prompt containing the context and user question.
        model: The OpenAI model used to generate the response.

    Returns:
        The text generated by the language model.

    Raises:
        ValueError: If the prompt is empty.
        RuntimeError: If the OpenAI API request fails.
    """
    if not prompt or not prompt.strip():
        raise ValueError("Prompt cannot be empty.")

    try:
        response = client.responses.create(
            model=model,
            input=prompt,
        )

        return response.output_text

    except Exception as error:
        raise RuntimeError(
            f"Failed to generate an answer from the OpenAI API: {error}"
        ) from error